# Generated by Django 5.2.8 on 2025-12-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_knowledgebase_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department_unit', models.CharField(blank=True, max_length=255)),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('contacts', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_beneficiaries', models.CharField(blank=True, max_length=255)),
                ('eligibility_criteria', models.CharField(blank=True, max_length=255)),
                ('workflows', models.CharField(blank=True, max_length=255)),
                ('timelines', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inquiry', 'Inquiry Handling'), ('complaint', 'Complaints Resolution'), ('application', 'Applications Processing')], max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('owner_role', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('responsibility', models.TextField(blank=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.ministryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3')])),
                ('target_role', models.CharField(max_length=255)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.workflow')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('workflow', 'level')},
            },
        ),
    ]
