# Generated by Django 5.2.8 on 2025-12-08 10:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ministryinfo_program_workflow_officerrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
          
            # Let the model definition handle the default
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'L1'), (2, 'L2'), (3, 'L3')],
                default=1
            ),
        ),
    ]