# Generated by Django 5.2.8 on 2025-12-16 13:53

import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_deadline_ticket_escalation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=backend.core.models.default_deadline),
        ),
    ]
