# Generated by Django 5.2.8 on 2025-12-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_youthprofile_documentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('youth', 'Youth'), ('officer', 'Officer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='youth', max_length=20),
        ),
    ]
