# Generated by Django 5.2.8 on 2026-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_middle_name_user_surname_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('youth', 'Youth'), ('officer', 'Officer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='youth', max_length=30),
        ),
        migrations.AlterField(
            model_name='youthprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='youthprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='youthprofile',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
