# Generated by Django 5.2.8 on 2026-01-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_message_receiver_alter_message_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
