# Generated by Django 5.2.8 on 2026-01-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ticket_sla_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketnote',
            old_name='content',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='core.ticket'),
        ),
    ]
