# Generated by Django 5.2.8 on 2026-02-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_ticket_deadline_auditlog_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
