# Generated by Django 5.2.8 on 2026-02-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
