# Generated by Django 5.2.8 on 2026-02-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_phone_number_youthprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='surname',
        ),
    ]
