# Generated by Django 5.2.8 on 2026-02-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_youthprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthprofile',
            name='lga',
        ),
    ]
