# Generated by Django 5.2.8 on 2026-02-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_youthprofile_lga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='youthprofile',
            old_name='verified_nin',
            new_name='nin_verified',
        ),
        migrations.RenameField(
            model_name='youthprofile',
            old_name='verified_voter_id',
            new_name='voter_id_verified',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='youthprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
